# Generated by Django 6.1.2 on 2026-10-06 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raphical', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-all_day', 'start']},
        ),
        migrations.AddField(
            model_name='event',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='color',
            field=models.CharField(choices=[('#d50000', 'Tomato'), ('#e67c73', 'Flamingo'), ('#f4511e', 'Tangerine'), ('#f6bf26', 'Banana'), ('#33b679', 'Sage'), ('#0b8043', 'Basil'), ('#039be5', 'Peacock'), ('#3f51b5', 'Blueberry'), ('#7986cb', 'Lavender'), ('#8e24aa', 'Grape'), ('#616161', 'Graphite')], default='#039be5', max_length=7),
        ),
    ]
