# Generated by Django 6.1.2 on 2026-10-06 14:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raphical', '0002_alter_event_options_event_all_day_event_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='color',
            field=models.CharField(default='#039be5', max_length=7, validators=[django.core.validators.RegexValidator('^#[0-9a-fA-F]{6}$', 'Enter a color like #1a73e8.')]),
        ),
    ]
