# Generated by Django 6.1.2 on 2026-10-06 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('raphical', '0005_pushsubscription_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='exdates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='original_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='rrule',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='event',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='raphical.event'),
        ),
        migrations.AddField(
            model_name='reminder',
            name='occurrence_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
